package com.wa2c.android.string_converter.repository

import com.wa2c.android.string_converter.model.CsvRow
import com.wa2c.android.string_converter.model.StringItem
import org.redundent.kotlin.xml.Element
import org.redundent.kotlin.xml.PrintOptions
import org.redundent.kotlin.xml.TextElement
import org.redundent.kotlin.xml.XmlVersion
import org.redundent.kotlin.xml.xml
import java.io.File

/**
 * Resource file repository
 */
class ResourceRepository {

    private val printOptions = PrintOptions(
        pretty = true,
        singleLineTextElements = true,
        indent = " ".repeat(4),
    )

    /**
     * Replace special characters
     */
    private fun String.replaceText(): String {
        return replace(Regex("\\r\\n|\\r|\\n"), "\\\\n")
            .replace(Regex("\'"), "\\\\'")
            .replace(Regex("\""), "\\\\\"")
    }

    /**
     * Save resource files
     */
    fun saveMultiLanguage(csvUrl: String, csvList: List<CsvRow>, resourceDirPath: String) {
        val nameRow = csvList.first().langText
        val stringMap = csvList.first().langText.keys.associateWith { mutableListOf<StringItem>() }
        var group = ""

        csvList.filter { it.resourceId.isNotEmpty() }.forEach { row ->
            if (row.title.isNotEmpty()) group = row.title
            row.langText.forEach { (langCode, text) ->
                stringMap[langCode]?.add(
                    StringItem(
                        group = group,
                        resourceId = row.resourceId,
                        value = text
                    )
                )
            }
        }

        stringMap.entries.map { entry ->

            val document = xml("resources", encoding = "utf-8", version= XmlVersion.V11) {
                comment("This file is generated by string converter tool.")
                comment("Source: $csvUrl")
                comment("Language: ${nameRow[entry.key]}")

                var currentGroup = ""

                entry.value.forEach { item ->
                    if (currentGroup != item.group) {
                        currentGroup = item.group
                        addElement(EmptyTextElement())
                        comment(currentGroup)
                    }
                    "string" {
                        attribute("name", item.resourceId)
                        -item.value.replaceText()
                    }
                }
            }

            val suffix = if (entry.key == "en") "" else "-${entry.key}"
            val dir = File(resourceDirPath + "/values${suffix}")
            if (!dir.exists()) dir.mkdirs()
            val file = File(dir, "strings.xml")
            if (!file.exists()) file.createNewFile()

            file.writeText(document.toString(printOptions) + "\n", XML_CHARSET)
            println("Updated: " + file.canonicalPath)
        }
    }

    open class EmptyTextElement() : Element {
        override fun render(builder: Appendable, indent: String, printOptions: PrintOptions) {
            val lineEnding = if (printOptions.pretty) System.lineSeparator() else ""
            builder.append("$indent$lineEnding")
        }

        override fun equals(other: Any?): Boolean = other is TextElement && other.text == ""

        override fun hashCode(): Int = "".hashCode()
    }

    companion object {
        private val XML_CHARSET = Charsets.UTF_8
    }
}
